// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentRegistration.Infrastructure.Data;

#nullable disable

namespace StudentRegistration.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251207163048_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentRegistration.Domain.Entities.ClassOffering", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcademicPeriod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<string>("OfferingCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.Property<string>("Schedule")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId");

                    b.HasIndex("SubjectId", "ProfessorId", "AcademicPeriod")
                        .IsUnique();

                    b.ToTable("ClassOfferings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AcademicPeriod = "2025-1",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MaxCapacity = 30,
                            OfferingCode = "MAT101-PROF001-2025-1",
                            ProfessorId = 1,
                            Schedule = "Lunes y Miércoles 8:00-10:00 AM",
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 2,
                            AcademicPeriod = "2025-1",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MaxCapacity = 30,
                            OfferingCode = "ALG101-PROF001-2025-1",
                            ProfessorId = 1,
                            Schedule = "Martes y Jueves 8:00-10:00 AM",
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 3,
                            AcademicPeriod = "2025-1",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MaxCapacity = 35,
                            OfferingCode = "PROG101-PROF002-2025-1",
                            ProfessorId = 2,
                            Schedule = "Lunes y Miércoles 10:00 AM-12:00 PM",
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 4,
                            AcademicPeriod = "2025-1",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MaxCapacity = 35,
                            OfferingCode = "WEB101-PROF002-2025-1",
                            ProfessorId = 2,
                            Schedule = "Martes y Jueves 10:00 AM-12:00 PM",
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 5,
                            AcademicPeriod = "2025-1",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MaxCapacity = 30,
                            OfferingCode = "DB101-PROF003-2025-1",
                            ProfessorId = 3,
                            Schedule = "Lunes y Miércoles 2:00-4:00 PM",
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 6,
                            AcademicPeriod = "2025-1",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MaxCapacity = 25,
                            OfferingCode = "CLOUD101-PROF003-2025-1",
                            ProfessorId = 3,
                            Schedule = "Martes y Jueves 2:00-4:00 PM",
                            SubjectId = 10
                        },
                        new
                        {
                            Id = 7,
                            AcademicPeriod = "2025-1",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MaxCapacity = 30,
                            OfferingCode = "NET101-PROF004-2025-1",
                            ProfessorId = 4,
                            Schedule = "Lunes y Miércoles 4:00-6:00 PM",
                            SubjectId = 6
                        },
                        new
                        {
                            Id = 8,
                            AcademicPeriod = "2025-1",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MaxCapacity = 25,
                            OfferingCode = "SEC101-PROF004-2025-1",
                            ProfessorId = 4,
                            Schedule = "Martes y Jueves 4:00-6:00 PM",
                            SubjectId = 7
                        },
                        new
                        {
                            Id = 9,
                            AcademicPeriod = "2025-1",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MaxCapacity = 25,
                            OfferingCode = "AI101-PROF005-2025-1",
                            ProfessorId = 5,
                            Schedule = "Lunes y Miércoles 6:00-8:00 PM",
                            SubjectId = 8
                        },
                        new
                        {
                            Id = 10,
                            AcademicPeriod = "2025-1",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MaxCapacity = 30,
                            OfferingCode = "MOB101-PROF005-2025-1",
                            ProfessorId = 5,
                            Schedule = "Martes y Jueves 6:00-8:00 PM",
                            SubjectId = 9
                        });
                });

            modelBuilder.Entity("StudentRegistration.Domain.Entities.CreditProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TotalCreditsRequired")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CreditPrograms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "PROG-STD",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Programa académico estándar con requisitos regulares de créditos",
                            IsActive = true,
                            Name = "Programa Estándar",
                            TotalCreditsRequired = 120
                        },
                        new
                        {
                            Id = 2,
                            Code = "PROG-INT",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Programa intensivo con mayor carga académica y menor duración",
                            IsActive = true,
                            Name = "Programa Intensivo",
                            TotalCreditsRequired = 150
                        },
                        new
                        {
                            Id = 3,
                            Code = "PROG-FLEX",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Programa flexible que permite al estudiante avanzar a su propio ritmo",
                            IsActive = true,
                            Name = "Programa Flexible",
                            TotalCreditsRequired = 100
                        });
                });

            modelBuilder.Entity("StudentRegistration.Domain.Entities.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassOfferingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("FinalGrade")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClassOfferingId");

                    b.HasIndex("StudentId", "ClassOfferingId")
                        .IsUnique();

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("StudentRegistration.Domain.Entities.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.ToTable("Professors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Matemáticas y Ciencias Básicas",
                            Email = "cmartinez@universidad.edu",
                            EmployeeCode = "PROF001",
                            FullName = "Dr. Carlos Alberto Martínez Ruiz",
                            IsActive = true,
                            Specialization = "Álgebra y Cálculo Avanzado"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Ingeniería de Software",
                            Email = "agarcia@universidad.edu",
                            EmployeeCode = "PROF002",
                            FullName = "Dra. Ana María García Fernández",
                            IsActive = true,
                            Specialization = "Programación Orientada a Objetos y Desarrollo Web"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Sistemas de Información",
                            Email = "lrodriguez@universidad.edu",
                            EmployeeCode = "PROF003",
                            FullName = "Dr. Luis Fernando Rodríguez López",
                            IsActive = true,
                            Specialization = "Bases de Datos y Sistemas Distribuidos"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Infraestructura y Redes",
                            Email = "mlopez@universidad.edu",
                            EmployeeCode = "PROF004",
                            FullName = "Dra. María del Carmen López Sánchez",
                            IsActive = true,
                            Specialization = "Redes de Computadoras y Seguridad Informática"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Inteligencia Artificial y Tecnologías Emergentes",
                            Email = "rsanchez@universidad.edu",
                            EmployeeCode = "PROF005",
                            FullName = "Dr. Roberto José Sánchez Torres",
                            IsActive = true,
                            Specialization = "Machine Learning y Cloud Computing"
                        });
                });

            modelBuilder.Entity("StudentRegistration.Domain.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreditProgramId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreditProgramId");

                    b.HasIndex("StudentNumber")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("StudentRegistration.Domain.Entities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Credits")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "MAT101",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credits = 3,
                            Description = "Fundamentos de álgebra, cálculo y matemáticas discretas",
                            IsActive = true,
                            Name = "Matemáticas Fundamentales"
                        },
                        new
                        {
                            Id = 2,
                            Code = "PROG101",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credits = 3,
                            Description = "Introducción a la programación orientada a objetos con C#",
                            IsActive = true,
                            Name = "Programación I"
                        },
                        new
                        {
                            Id = 3,
                            Code = "DB101",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credits = 3,
                            Description = "Diseño, modelado e implementación de bases de datos relacionales",
                            IsActive = true,
                            Name = "Bases de Datos"
                        },
                        new
                        {
                            Id = 4,
                            Code = "WEB101",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credits = 3,
                            Description = "Desarrollo de aplicaciones web con HTML, CSS, JavaScript y frameworks modernos",
                            IsActive = true,
                            Name = "Desarrollo Web"
                        },
                        new
                        {
                            Id = 5,
                            Code = "ALG101",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credits = 3,
                            Description = "Análisis y diseño de algoritmos eficientes",
                            IsActive = true,
                            Name = "Algoritmos y Estructuras de Datos"
                        },
                        new
                        {
                            Id = 6,
                            Code = "NET101",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credits = 3,
                            Description = "Fundamentos de redes, protocolos TCP/IP y arquitecturas de red",
                            IsActive = true,
                            Name = "Redes de Computadoras"
                        },
                        new
                        {
                            Id = 7,
                            Code = "SEC101",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credits = 3,
                            Description = "Principios de seguridad, criptografía y protección de sistemas",
                            IsActive = true,
                            Name = "Seguridad Informática"
                        },
                        new
                        {
                            Id = 8,
                            Code = "AI101",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credits = 3,
                            Description = "Fundamentos de IA, machine learning y deep learning",
                            IsActive = true,
                            Name = "Inteligencia Artificial"
                        },
                        new
                        {
                            Id = 9,
                            Code = "MOB101",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credits = 3,
                            Description = "Desarrollo de aplicaciones móviles multiplataforma",
                            IsActive = true,
                            Name = "Desarrollo Móvil"
                        },
                        new
                        {
                            Id = 10,
                            Code = "CLOUD101",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credits = 3,
                            Description = "Computación en la nube con Azure, AWS y arquitecturas distribuidas",
                            IsActive = true,
                            Name = "Cloud Computing"
                        });
                });

            modelBuilder.Entity("StudentRegistration.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Student");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("StudentRegistration.Domain.Entities.ClassOffering", b =>
                {
                    b.HasOne("StudentRegistration.Domain.Entities.Professor", "Professor")
                        .WithMany("ClassOfferings")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentRegistration.Domain.Entities.Subject", "Subject")
                        .WithMany("ClassOfferings")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Professor");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("StudentRegistration.Domain.Entities.Enrollment", b =>
                {
                    b.HasOne("StudentRegistration.Domain.Entities.ClassOffering", "ClassOffering")
                        .WithMany("Enrollments")
                        .HasForeignKey("ClassOfferingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentRegistration.Domain.Entities.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassOffering");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentRegistration.Domain.Entities.Student", b =>
                {
                    b.HasOne("StudentRegistration.Domain.Entities.CreditProgram", "CreditProgram")
                        .WithMany("Students")
                        .HasForeignKey("CreditProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentRegistration.Domain.Entities.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("StudentRegistration.Domain.Entities.Student", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreditProgram");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudentRegistration.Domain.Entities.ClassOffering", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("StudentRegistration.Domain.Entities.CreditProgram", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("StudentRegistration.Domain.Entities.Professor", b =>
                {
                    b.Navigation("ClassOfferings");
                });

            modelBuilder.Entity("StudentRegistration.Domain.Entities.Student", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("StudentRegistration.Domain.Entities.Subject", b =>
                {
                    b.Navigation("ClassOfferings");
                });

            modelBuilder.Entity("StudentRegistration.Domain.Entities.User", b =>
                {
                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
